config/routes.rb
Rails.application.routes.draw do

  root 'libros#index'

  resources :libros do
    member do 
      get 'upload', to: 'libros#upload'
      patch 'upload', to: 'libros#do_upload'
      get 'resume_upload', to: 'libros#resume_upload'
      patch 'update_status', to: 'libros#update_status'
      get 'reset_upload', to: 'libros#reset_upload'
    end
  end

end

app/models/libro.rb
class Libro < ActiveRecord::Base
  # Variables
  LIBRO_STATUSES = %w(new uploading uploaded)

  # Validations
  validates :title, presence: true
  validates :status, inclusion: { in: LIBRO_STATUSES }

  # Paperclip
  has_attached_file :upload, url: "/:basename.:extension"
  validates_attachment :upload, content_type: { content_type: ['application/zip', 'application/pdf'] }

  before_save :save_thumbnail
  def save_thumbnail
    p '*****************************************************'
    p '*****************************************************'
    if Dir.glob(Rails.root.join('public', '*.pdf')).any?
      filename = ''
      Dir.glob(Rails.root.join('public', '*.pdf')) {|file_name|
        filename =  file_name
        image = StorageBucket.files.new(
          key: File.basename(filename),
          body: File.read(Rails.root.join('public', filename)),
          public: true
        )
        image.save
        @hypdf_response = HyPDF.pdfextract(
          Rails.root.join('public', filename),
          user: 'victorcasas.sm@gmail.com',
          password: '12cscv01',
          first_page: 1,
          last_page: 1
        )
        File.open(Rails.root.join('public', filename), 'wb') do |file|
          file.write(@hypdf_response[:pdf])
        end
        pdf = Magick::ImageList.new(Rails.root.join('public', filename))
        pdf.first.write(Rails.root.join('public', filename + '.jpg'))
        image2 = StorageBucket.files.new(
          key: File.basename(filename) + '.jpg',
          body: File.read(Rails.root.join('public', filename + '.jpg')),
          public: true
        )
        image2.save
        File.delete(Rails.root.join('public', filename))
        File.delete(Rails.root.join('public', filename + '.jpg'))
        self.imageurl =   image.public_url
        self.coverurl =   image2.public_url
      }
    end
  end
  
  def to_jq_upload(error=nil)
    {
      files: [
        {
          name: read_attribute(:upload_file_name),
          size: read_attribute(:upload_file_size),
          url: upload.url(:original),
          delete_url: Rails.application.routes.url_helpers.libro_path(self),
          delete_type: "DELETE" 
        }
      ]
    }
  end

  def upload_done?
    status.in? %w(uploaded) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy, :upload, :do_upload, :resume_upload, :update_status, :reset_upload]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all.order(title: :asc)
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
    # If upload is not commenced or finished, redirect to upload page
    return redirect_to upload_libro_path(@libro) if @libro.status.in?(%w(new uploading))
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)
    @libro.status = 'new'

    respond_to do |format|
      if @libro.save
        format.html { redirect_to upload_libro_path(@libro), notice: 'Libro creado con éxito.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    destroy if params[:delete_upload] == 'sí'

    unless @libro.destroyed?
      respond_to do |format|
        if @libro.update(libro_params)
          format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
          format.json { render :show, status: :ok, location: @libro }
        else
          format.html { render :edit }
          format.json { render json: @libro.errors, status: :unprocessable_entity }
        end
      end
    end  
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /libros/:id/upload
  def upload

  end

  # PATCH /libros/:id/upload.json
  def do_upload
    unpersisted_libro = Libro.new(upload_params)

    # If no file has been uploaded or the uploaded file has a different filename,
    # do a new upload from scratch
    if @libro.upload_file_name != unpersisted_libro.upload_file_name
      @libro.assign_attributes(upload_params)
      @libro.status = 'uploading'
      @libro.save!
      render json: @libro.to_jq_upload and return

    # If the already uploaded file has the same filename, try to resume
    else
      current_size = @libro.upload_file_size
      content_range = request.headers['CONTENT-RANGE']
      begin_of_chunk = content_range[/\ (.*?)-/,1].to_i # "bytes 100-999999/1973660678" will return '100'

      # If the there is a mismatch between the size of the incomplete upload and the content-range in the
      # headers, then it's the wrong chunk! 
      # In this case, start the upload from scratch
      unless begin_of_chunk == current_size
        @libro.update!(upload_params)
        render json: @libro.to_jq_upload and return
      end
      
      # Add the following chunk to the incomplete upload
      File.open(@libro.upload.path, "ab") { |f| f.write(upload_params[:upload].read) }

      # Update the upload_file_size attribute
      @libro.upload_file_size = @libro.upload_file_size.nil? ? unpersisted_libro.upload_file_size : @libro.upload_file_size + unpersisted_libro.upload_file_size
      @libro.save!

      render json: @libro.to_jq_upload and return
    end
  end

  # GET /libros/:id/reset_upload
  def reset_upload
    # Allow users to delete uploads only if they are incomplete
    raise StandardError, "Action not allowed" unless @libro.status == 'uploading'
    @libro.update!(status: 'new', upload: nil)
    redirect_to @libro, notice: "Upload reset successfully. You can now start over"
  end

  # GET /libros/:id/resume_upload.json
  def resume_upload
    render json: { file: { name: @libro.upload.url(:default, timestamp: false), size: @libro.upload_file_size } } and return
  end

  # PATCH /libros/:id/update_upload_status
  def update_status
    raise ArgumentError, "Wrong status provided " + params[:status] unless @libro.status == 'uploading' && params[:status] == 'uploaded'
    @libro.update!(status: params[:status])
    head :ok
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_libro
    @libro = Libro.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def libro_params
    params.require(:libro).permit(:title, :author, :published_on, :description, :imageurl, :coverurl)
  end

  def upload_params
    params.require(:libro).permit(:upload)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libros_helper.rb
module LibrosHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = "Libros para compartir con amigos"

    %meta{ content: 'minimum-scale=1.0, width=device-width, maximum-scale=1, user-scalable=no', name: 'viewport' }
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }
    %meta{ name: 'apple-touch-fullscreen', content: 'yes' }

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body{ data: { controller: controller_name, action: action_name } }
    = render 'shared/topbar'
    .container
      = notice
      = yield

app/views/libros/0index.html.haml
%h1 
  Todos los libros
  = link_to 'Añadir nuevo libro', new_libro_path, class: "btn btn-large btn-success"
%hr
.padding-bottom
  - @libros.each do |libro|
    = link_to libro.title, libro
    = image_tag libro.coverurl

app/views/libros/_form.html.haml
= form_for @libro, html: { multipart: true, id: "fileupload" } do |f|
  - if @libro.errors.any?
    #error_explanation
      %h2= "#{pluralize(@libro.errors.count, "error")} prohibited this libro from being saved:"
      %ul
        - @libro.errors.full_messages.each do |msg|
          %li= msg
  .col-md-5
    .row
      %h3
        Título
      .padding-left
        = f.text_field :title
  .col-md-5
    .row
      %h3
        Autor
      .padding-left
        = f.text_field :author
  .col-md-5
    .row
      %h3
        Fecha de publicación
      .padding-left
        = f.date_field :published_on 
      
  .col-md-5
    .row
      %h3
        Descripción
      .padding-left
        = f.text_area :description

    - if @libro.upload_done?
      .row  
        %h3
          Uploaded file
        .padding-left
          .row
            = @libro.upload_file_name + " (" + number_to_human_size(@libro.upload_file_size.to_s) + ")"
          .row
            = check_box_tag :delete_upload, 'sí', false
            = label_tag :delete_upload, 'borrar este archivo', class: 'text-danger'
    
    .empty-space
    .row
      - submit_text = controller_name == 'new' ? "Crear" : "Guardar"
      = f.submit submit_text, class: "btn btn-success"

app/views/libros/edit.html.haml
%h1 Edicion de libro

= render 'form'

= link_to 'Mostrar', @libro
\|
= link_to 'Volver', libros_path

app/views/libros/index.html.erb
<h1>Todos los libros</h1>
<%= link_to new_libro_path, class: "btn btn-lg btn-success" do %>
  <i class="glyphicon glyphicon-plus"></i>
  <span>Añadir nuevo libro</span>
<% end %>
<br><br>
<% @libros.each do |libro| %>
  <div class="book">
    <%= link_to libro_path(libro) do %>
    <div class="col-sm-3 text-center" multilinks-noscroll="true" >
      <div class="imagen">
        <img class="img-responsive" src="<%= libro.coverurl %>" >
     </div>
    </div>
    <% end %>
  </div>
<% end %>

app/views/libros/new.html.haml
%h1 Nuevo libro
%hr

= render 'form'

app/views/libros/show.html.haml
%h1
  = @libro.title
  = link_to content_tag(:i, "", class: "glyphicon glyphicon-pencil"), edit_libro_path(@libro)
.padding-left
  .row
    = image_tag @libro.coverurl, class: "img-responsive"
  .row
    = @libro.upload_file_name + " (" + number_to_human_size(@libro.upload_file_size.to_s) + ")"
  .row
    = link_to content_tag(:i, "", class: "glyphicon glyphicon-download") + " Descargar", @libro.imageurl, class: "btn btn-lg btn-success"

app/views/libros/upload.html.haml
%h1
  Subir un archivo PDF
%hr

= form_for @libro, url: upload_libro_path, method: :post, html: { multipart: true, id: "fileupload" } do |f|
  .row
    %h3
      Título del libro
    .padding-left
      = @libro.title
  
  .row.empty-space

  .row 
    - unless @libro.status == 'uploading'
      .alert.alert-success.smaller-text
        Para comenzar una subida seleccionar un archivo del ordenador.
    - else
      .alert.alert-warning.smaller-text
        The system detected an unfinished upload. To resume it, please select the same file and press the green button. <br />
        Resume not working or receiving error messages? Then please click #{link_to 'here', reset_upload_libro_path(@libro)} to delete the temoporary file and start over.

  .row.fileupload-buttonbar
    #js-data{ data: { libro: @libro.id } }
    .col-lg-7
      .btn.btn-primary.fileinput-button
        %i.glyphicon.glyphicon-plus
        Seleccionar un archivo
        = f.file_field :upload

  %table.table.table-striped#js-file-container{ role: "presentation" }
    %tbody.files

:javascript
  $(document).ready(function () {
    var libro_id = $('#js-data').data('libro');
    var controller_name = $('body').data('controller');
    var model_instance_path = '/' + controller_name + '/' + libro_id;
    var resume_path = model_instance_path + '/resume_upload';
    var update_status_path = model_instance_path + '/update_status';

    $('#fileupload').fileupload({
      maxNumberOfFiles: 1,
      maxChunkSize: 10000000, // 10 MB
      type: 'PATCH',
      add: function (e, data) {
        var that = this;
        $.getJSON(resume_path, { file: data.files[0].name }, function (result) {
            var file = result.file;
            data.uploadedBytes = file && file.size;
            $.blueimp.fileupload.prototype
                .options.add.call(that, e, data);
        });
      }
    });

    $('#fileupload')
      .bind('fileuploadchunkdone', function (e, data) {
        var perc = parseInt(data.loaded / data.total * 100, 10);
        $('#js-completed').html(perc + "%");
      })
      .bind('fileuploaddone', function (e, data) {
        $.ajax({
          url: update_status_path,
          type: "PATCH",
          data: { status: 'uploaded'},
          success: function(data) {
            window.location.replace(model_instance_path);
          } 
        });
      });
    });

:plain
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-upload fade">

            <td width="45%">
                <p class="name"><h3>{%=file.name%}</h3></p>
                <p class="size">Procesando...</p>
                <strong class="error text-danger"></strong>

                {% if (!i && !o.options.autoUpload) { %}
                    <button class="btn btn-success start" disabled>
                        <i class="glyphicon glyphicon-upload"></i>
                        Empezar / continuar
                    </button> 
                {% } %}
                {% if (!i) { %}
                    <button class="btn btn-danger cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        Cancelar subida
                    </button>
                {% } %}
            </td>
            <td width="45%" style="vertical-align: middle;">
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
                <p><h1 id="js-completed" align="center"></h1></p>
            </td>
        </tr>
    {% } %}
  </script>

  <script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
        <tr class="template-download fade">
            <td>
                <span class="preview">
                    {% if (file.thumbnailUrl) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                    {% } %}
                </span>
            </td>
            <td>
                <p class="name">
                    {% if (file.url) { %}
                        <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                    {% } else { %}
                        <span>{%=file.name%}</span>
                    {% } %}
                </p>
                {% if (file.error) { %}
                    <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                {% } %}
            </td>
            <td>
                <span class="size">{%=o.formatFileSize(file.size)%}</span>
            </td>
            <td>
                {% if (file.deleteUrl) { %}
                    <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                        <i class="glyphicon glyphicon-trash"></i>
                        <span>Delete</span>
                    </button>
                    <input type="checkbox" name="delete" value="1" class="toggle">
                {% } else { %}
                    <button class="btn btn-warning cancel">
                        <i class="glyphicon glyphicon-ban-circle"></i>
                        <span>Cancel</span>
                    </button>
                {% } %}
            </td>
        </tr>
      {% } %}
    </script>

app/views/shared/_topbar.html.haml
.navbar.navbar-default
  .container
    .navbar-header
      %btn.navbar-toggle.collapsed{ data: { toggle: "collapse", target: "#bs-example-navbar-collapse-1" }}
        %span.sr-only
          Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Libros para compartir con amigos...", root_path, class: "navbar-brand"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav
        %li
-#          = link_to "Todos los libros", libros_path, class: 'nav-link'